# Names Analysis

analylize name data from [census.gov](https://www.census.gov/topics/population/genealogy/data/2020_names.html)

### check

In [3]:
print("kernel is working")

kernel is working

### imports

In [101]:
from urllib import request
from pathlib import Path
import pandas
import numpy as np
from pandas import DataFrame
from pandas import Series

### Download Data

In [5]:
ASSETS_DIR = Path("assets")
ASSETS_DIR.mkdir(exist_ok=True)

FIRST_NAMES_URL = r"https://www2.census.gov/topics/genealogy/2020surnames/Names2020_FirstNames_Sex.xlsx"
FIRST_NAMES_FILE = ASSETS_DIR / "first-names.xlsx"
LAST_NAMES_URL = r"https://www2.census.gov/topics/genealogy/2020surnames/Names2020_LastNames_RaceHispanic.xlsx"
LAST_NAMES_FILE = ASSETS_DIR / "last-names.xlsx"

_ = request.urlretrieve(FIRST_NAMES_URL, FIRST_NAMES_FILE)
_ = request.urlretrieve(LAST_NAMES_URL, LAST_NAMES_FILE)

### Load/Visualize Data

In [ ]:
first_names = pandas.read_excel(  # pyright: ignore[reportUnknownMemberType]
    FIRST_NAMES_FILE, skiprows=2
)
first_names = first_names[:-1]  # drop "ALL OTHER NAMES"
first_names

,FIRST NAME,RANK,FREQUENCY (COUNT),"PROPORTION PER 100,000 POPULATION",CUMULATIVE PROPORTION,MALE,FEMALE
0,MICHAEL,1.0,3476721,1151.111916,1151.111916,3469434,7287
1,JOHN,2.0,3125123,1034.700893,2185.812809,3118620,6503
2,JAMES,3.0,2996421,992.088786,3177.901595,2992500,3921
3,DAVID,4.0,2813017,931.365326,4109.266921,2810463,2554
4,ROBERT,5.0,2759339,913.593010,5022.859931,2756604,2735
...,...,...,...,...,...,...,...
53610,SCHUBERT,53603.0,94,0.031123,93777.115049,93,1
53611,TAMPA,53603.0,94,0.031123,93777.146172,15,79
53612,CHILDS,53613.0,93,0.030791,93777.176963,56,37
53613,DOGLAS,53614.0,91,0.030129,93777.207093,91,0
53614,JESUE,53614.0,91,0.030129,93777.237222,90,1

In [107]:
last_names = pandas.read_excel(  # pyright: ignore[reportUnknownMemberType]
    LAST_NAMES_FILE, skiprows=2
)
last_names = last_names[:-1]  # drop "ALL OTHER NAMES"
last_names

,LAST NAME,RANK,FREQUENCY (COUNT),"PROPORTION PER 100,000 POPULATION",CUMULATIVE PROPORTION,NON-HISPANIC OR LATINO WHITE ALONE,NON-HISPANIC OR LATINO BLACK OR AFRICAN AMERICAN ALONE,NON-HISPANIC OR LATINO AMERICAN INDIAN AND ALASKA NATIVE ALONE,NON-HISPANIC OR LATINO ASIAN AND NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE,NON-HISPANIC OR LATINO TWO OR MORE RACES,HISPANIC OR LATINO ORIGIN
0,SMITH,1.0,2369644,792.792916,792.792916,1611236,535967,19744,16139,103611,82947
1,JOHNSON,2.0,1858234,621.694546,1414.487461,1055206,623699,16365,13156,87789,62019
2,WILLIAMS,3.0,1561395,522.383486,1936.870948,684271,721683,12205,9209,79393,54634
3,BROWN,4.0,1386083,463.730747,2400.601695,768332,480749,11738,9160,66938,49166
4,JONES,5.0,1383250,462.782933,2863.384628,733895,514871,12618,8184,67406,46276
...,...,...,...,...,...,...,...,...,...,...,...
156616,HOGEBACK,156616.0,93,0.031114,87869.447110,91,0,0,0,2,0
156617,KEETO,156616.0,93,0.031114,87869.478224,4,0,85,0,0,4
156618,PYETT,156616.0,93,0.031114,87869.509338,49,40,0,0,4,0
156619,UTENDORF,156616.0,93,0.031114,87869.540452,93,0,0,0,0,0
156620,DREWNO,156621.0,92,0.030780,87869.571232,80,0,0,0,0,12

### analysis

In [43]:
result = first_names.query(  # pyright: ignore[reportUnknownMemberType]
    '`FIRST NAME`=="ALLEN"'
)
result

,FIRST NAME,RANK,FREQUENCY (COUNT),"PROPORTION PER 100,000 POPULATION",CUMULATIVE PROPORTION,MALE,FEMALE
331,ALLEN,332.0,166924,55.267076,50851.794827,166027,897

In [ ]:
# first_letter = first_names["FIRST NAME"].apply(lambda row: row[0])
# first_names["first_letter"] = first_letter
# first_letters = first_names.groupby("first_letter")
# desired_field = "PROPORTION PER 100,000 POPULATION"
# letter_frequencies = first_letters[desired_field].aggregate(np.sum).sort_values(ascending=False)
# letter_frequencies /= 100000 # into fraction of one
# total_percent = letter_frequencies.sum()
# letter_frequencies /= total_percent # normalize so sum=1 (currently doesn't because 'other' is droped)
# letter_frequencies * 100


def calculate_letter_frequency(df: DataFrame, column: str) -> Series:
    first_letter = df[column].apply(lambda row: row[0])
    first_names["first_letter"] = first_letter
    first_letters = first_names.groupby("first_letter")
    desired_field = "PROPORTION PER 100,000 POPULATION"
    letter_frequencies = (
        first_letters[desired_field].aggregate(np.sum).sort_values(ascending=False)
    )
    letter_frequencies /= 100000  # into fraction of one
    total_percent = letter_frequencies.sum()
    letter_frequencies /= total_percent  # normalize so sum=1 (currently doesn't because 'other' is droped)
    return letter_frequencies

In [109]:
letter_frequencies_first_name = calculate_letter_frequency(first_names,"FIRST NAME")
letter_frequencies_first_name

first_letter
J    0.126283
M    0.097412
A    0.091255
C    0.073522
S    0.069002
D    0.066385
R    0.062033
K    0.053873
L    0.052883
B    0.045292
E    0.044470
T    0.042404
G    0.028978
P    0.026598
N    0.025277
H    0.020637
W    0.017063
V    0.013401
F    0.012385
I    0.010735
O    0.006924
Z    0.005442
Y    0.004864
X    0.001219
Q    0.001018
U    0.000643
Name: PROPORTION PER 100,000 POPULATION, dtype: float64

In [108]:
letter_frequencies_last_name = calculate_letter_frequency(last_names,"LAST NAME")
letter_frequencies_last_name

TypeError: 'float' object is not subscriptable